<a href="https://colab.research.google.com/github/youssefbourais0310/Neural_Networks/blob/main/Neural_Networks_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creates a simple layer of neurons, with 4 inputs

In [1]:
inputs =  [1, 2, 3, 2.5]
wieghts = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = inputs[0]*wieghts[0] + inputs[1]*wieghts[1] + inputs[2]*wieghts[2] + inputs[3]*wieghts[3] +bias
print(output)

4.8


Creates a simple layer of 3 neurons, with 4 inputs

In [2]:
inputs =  [1, 2, 3, 2.5]
wieghts1 = [0.2, 0.8, -0.5, 1.0]
wieghts2 = [0.5, -0.91, 0.26, -0.5]
wieghts3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5


output = [[inputs[0]*wieghts1[0] + inputs[1]*wieghts1[1] + inputs[2]*wieghts1[2] + inputs[3]*wieghts1[3] +bias1],
          [inputs[0]*wieghts2[0] + inputs[1]*wieghts2[1] + inputs[2]*wieghts2[2] + inputs[3]*wieghts2[3] +bias2],
          [inputs[0]*wieghts3[0] + inputs[1]*wieghts3[1] + inputs[2]*wieghts3[2] + inputs[3]*wieghts3[3] +bias3]]
print(output)

[[4.8], [1.21], [2.385]]


Creates a simple layer of neurons, with 4 inputs (dynamic code)

In [3]:
inputs =  [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = [] #output of current layer
for neuron_weights, neuron_bias in zip(weights,biases):
    neuron_output = 0 #output of given neuron
    for n_input,weights in zip(inputs, neuron_weights):
          neuron_output += n_input*weights
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


Creates a simple layer of neurons, with 4 inputs using numpy

In [4]:
import numpy as np

inputs =  [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]    
bias = 2

output = np.dot(inputs, weights) + bias
print(output)


4.8


Creates a simple layer of 3 neurons, with 4 inputs using numpy

In [5]:
import numpy as np
inputs =  [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(weights ,inputs) + biases
print(output)

[4.8   1.21  2.385]


Creates 2 layer of 3 neurons, with 4 inputs using numpy

In [6]:
import numpy as np

inputs =  [[1, 2, 3, 2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs ,np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs ,np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [7]:
import numpy as np


X =  [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]
     

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
       self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
       self.biases = np.zeros((1,n_neurons))
  def forward(self,inputs):
       self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[ 0.00677106  0.05921988]
 [ 0.04648762  0.01201874]
 [ 0.07965833 -0.05214135]]
